/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * elegirZombieQueViene.java
 *
 * Created on 28-jun-2011, 23:59:18
 */

package plantasvszombies;

import java.awt.Graphics;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ListIterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author Francis
 */
public class elegirZombieQueViene extends javax.swing.JFrame {
    
    private ImageIcon zombie = new ImageIcon("imagenes/Zombies/zombieNormal.jpg");
    private ImageIcon zombieCono = new ImageIcon("imagenes/Zombies/zombieCono.jpg");
    private ImageIcon zombieCubo = new ImageIcon("imagenes/Zombies/zombieCubo.jpg");
    private ImageIcon zombiePuerta = new ImageIcon("imagenes/Zombies/zombiePuerta.jpg");
    private ImageIcon zombieLanza = new ImageIcon("imagenes/Zombies/zombieLanza.jpg");
    private ImageIcon zombieRugby = new ImageIcon("imagenes/Zombies/zombieRugby.jpg");
    private ImageIcon zombieLoco = new ImageIcon("imagenes/Zombies/zombieLoco.jpg");
    private ImageIcon zombieGlobo = new ImageIcon("imagenes/Zombies/zombieGlobo.jpg");
    private ImageIcon zombieCatapulta = new ImageIcon("imagenes/Zombies/zombieCatapulta.jpg");
    private ImageIcon zombieYeti = new ImageIcon("imagenes/Zombies/zombieYeti.jpg");
    private ImageIcon zombieGigante = new ImageIcon("imagenes/Zombies/zombieGigante.jpg");
    private ImageIcon zombieMinero = new ImageIcon("imagenes/Zombies/zombieMinero.jpg");
    private ImageIcon zombiePeriodico = new ImageIcon("imagenes/Zombies/zombiePeriodico.jpg");

    private zombie zombi;
    private int fil;
    private ArrayList zombs;
    private boolean empezarAElegir = false;
    /** Creates new form elegirZombieQueViene */
    public elegirZombieQueViene() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public zombie getZombiQueViene(){
        return zombi;
    }

    public int getFilaDelZombi(){
        return fil;
    }

    public elegirZombieQueViene(ArrayList zombies, zombie z, int fila) throws LineUnavailableException, IOException, UnsupportedAudioFileException {
        zombi = z;
        fil = fila;
        zombs = zombies;
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelZombieNormal = new javax.swing.JPanel();
        panelZombieCono = new javax.swing.JPanel();
        panelZombieCubo = new javax.swing.JPanel();
        panelZombiePeriodico = new javax.swing.JPanel();
        panelZombiePuerta = new javax.swing.JPanel();
        panelZombieLanza = new javax.swing.JPanel();
        panelZombieCatapulta = new javax.swing.JPanel();
        panelZombieGigante = new javax.swing.JPanel();
        panelZombieMinero = new javax.swing.JPanel();
        panelZombieGlobo = new javax.swing.JPanel();
        panelZombieLoco = new javax.swing.JPanel();
        panelZombieYeti = new javax.swing.JPanel();
        panelZombieRugby = new javax.swing.JPanel();
        textoFilaZombie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonElegirZombie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelZombieNormal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelZombieNormal.setMaximumSize(new java.awt.Dimension(10000, 10000));
        panelZombieNormal.setMinimumSize(new java.awt.Dimension(1000, 1000));
        panelZombieNormal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelZombieNormalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelZombieNormalLayout = new javax.swing.GroupLayout(panelZombieNormal);
        panelZombieNormal.setLayout(panelZombieNormalLayout);
        panelZombieNormalLayout.setHorizontalGroup(
            panelZombieNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        panelZombieNormalLayout.setVerticalGroup(
            panelZombieNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        panelZombieCono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelZombieCono.setMaximumSize(new java.awt.Dimension(1000, 1000));
        panelZombieCono.setMinimumSize(new java.awt.Dimension(1000, 1000));
        panelZombieCono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelZombieConoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelZombieConoLayout = new javax.swing.GroupLayout(panelZombieCono);
        panelZombieCono.setLayout(panelZombieConoLayout);
        panelZombieConoLayout.setHorizontalGroup(
            panelZombieConoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        panelZombieConoLayout.setVerticalGroup(
            panelZombieConoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        panelZombieCubo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelZombieCubo.setPreferredSize(new java.awt.Dimension(62, 100));
        panelZombieCubo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelZombieCuboMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelZombieCuboLayout = new javax.swing.GroupLayout(panelZombieCubo);
        panelZombieCubo.setLayout(panelZombieCuboLayout);
        panelZombieCuboLayout.setHorizontalGroup(
            panelZombieCuboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panelZombieCuboLayout.setVerticalGroup(
            panelZombieCuboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        panelZombiePeriodico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelZombiePeriodico.setPreferredSize(new java.awt.Dimension(75, 100));
        panelZombiePeriodico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelZombiePeriodicoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelZombiePeriodicoLayout = new javax.swing.GroupLayout(panelZombiePeriodico);
        panelZombiePeriodico.setLayout(panelZombiePeriodicoLayout);
        panelZombiePeriodicoLayout.setHorizontalGroup(
            panelZombiePeriodicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
        panelZombiePeriodicoLayout.setVerticalGroup(
            panelZombiePeriodicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        panelZombiePuerta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelZombiePuerta.setPreferredSize(new java.awt.Dimension(76, 100));
        panelZombiePuerta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelZombiePuertaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelZombiePuertaLayout = new javax.swing.GroupLayout(panelZombiePuerta);
        panelZombiePuerta.setLayout(panelZombiePuertaLayout);
        panelZombiePuertaLayout.setHorizontalGroup(
            panelZombiePuertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
        panelZombiePuertaLayout.setVerticalGroup(
            panelZombiePuertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        panelZombieLanza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelZombieLanza.setPreferredSize(new java.awt.Dimension(75, 100));
        panelZombieLanza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelZombieLanzaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelZombieLanzaLayout = new javax.swing.GroupLayout(panelZombieLanza);
        panelZombieLanza.setLayout(panelZombieLanzaLayout);
        panelZombieLanzaLayout.setHorizontalGroup(
            panelZombieLanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
        panelZombieLanzaLayout.setVerticalGroup(
            panelZombieLanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        panelZombieCatapulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelZombieCatapulta.setPreferredSize(new java.awt.Dimension(123, 100));
        panelZombieCatapulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelZombieCatapultaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelZombieCatapultaLayout = new javax.swing.GroupLayout(panelZombieCatapulta);
        panelZombieCatapulta.setLayout(panelZombieCatapultaLayout);
        panelZombieCatapultaLayout.setHorizontalGroup(
            panelZombieCatapultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );
        panelZombieCatapultaLayout.setVerticalGroup(
            panelZombieCatapultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        panelZombieGigante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelZombieGigante.setPreferredSize(new java.awt.Dimension(58, 100));
        panelZombieGigante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelZombieGiganteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelZombieGiganteLayout = new javax.swing.GroupLayout(panelZombieGigante);
        panelZombieGigante.setLayout(panelZombieGiganteLayout);
        panelZombieGiganteLayout.setHorizontalGroup(
            panelZombieGiganteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        panelZombieGiganteLayout.setVerticalGroup(
            panelZombieGiganteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        panelZombieMinero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelZombieMinero.setPreferredSize(new java.awt.Dimension(70, 100));
        panelZombieMinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelZombieMineroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelZombieMineroLayout = new javax.swing.GroupLayout(panelZombieMinero);
        panelZombieMinero.setLayout(panelZombieMineroLayout);
        panelZombieMineroLayout.setHorizontalGroup(
            panelZombieMineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        panelZombieMineroLayout.setVerticalGroup(
            panelZombieMineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        panelZombieGlobo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelZombieGlobo.setPreferredSize(new java.awt.Dimension(60, 100));
        panelZombieGlobo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelZombieGloboMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelZombieGloboLayout = new javax.swing.GroupLayout(panelZombieGlobo);
        panelZombieGlobo.setLayout(panelZombieGloboLayout);
        panelZombieGloboLayout.setHorizontalGroup(
            panelZombieGloboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        panelZombieGloboLayout.setVerticalGroup(
            panelZombieGloboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        panelZombieLoco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelZombieLoco.setPreferredSize(new java.awt.Dimension(80, 100));
        panelZombieLoco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelZombieLocoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelZombieLocoLayout = new javax.swing.GroupLayout(panelZombieLoco);
        panelZombieLoco.setLayout(panelZombieLocoLayout);
        panelZombieLocoLayout.setHorizontalGroup(
            panelZombieLocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        panelZombieLocoLayout.setVerticalGroup(
            panelZombieLocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        panelZombieYeti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelZombieYeti.setPreferredSize(new java.awt.Dimension(92, 145));
        panelZombieYeti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelZombieYetiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelZombieYetiLayout = new javax.swing.GroupLayout(panelZombieYeti);
        panelZombieYeti.setLayout(panelZombieYetiLayout);
        panelZombieYetiLayout.setHorizontalGroup(
            panelZombieYetiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        panelZombieYetiLayout.setVerticalGroup(
            panelZombieYetiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        panelZombieRugby.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelZombieRugby.setPreferredSize(new java.awt.Dimension(86, 100));
        panelZombieRugby.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelZombieRugbyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelZombieRugbyLayout = new javax.swing.GroupLayout(panelZombieRugby);
        panelZombieRugby.setLayout(panelZombieRugbyLayout);
        panelZombieRugbyLayout.setHorizontalGroup(
            panelZombieRugbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );
        panelZombieRugbyLayout.setVerticalGroup(
            panelZombieRugbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        textoFilaZombie.setText("0");

        jLabel1.setText("Fila por la que viene el zombie");

        botonElegirZombie.setText("Elegir zombie");
        botonElegirZombie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonElegirZombieMouseClicked(evt);
            }
        });
        botonElegirZombie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElegirZombieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(panelZombieNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelZombieCono, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelZombieCubo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelZombiePeriodico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelZombiePuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelZombieLanza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(panelZombieLoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelZombieGlobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelZombieMinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelZombieGigante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelZombieCatapulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(panelZombieYeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelZombieRugby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(textoFilaZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonElegirZombie))
                                .addComponent(jLabel1))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(panelZombieLanza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelZombiePuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelZombiePeriodico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelZombieCubo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelZombieCono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelZombieNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelZombieCatapulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelZombieLoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelZombieGlobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelZombieMinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelZombieGigante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelZombieRugby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelZombieYeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonElegirZombie)
                                .addComponent(textoFilaZombie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint(Graphics g)
    {
        super.paintComponents(g);
        g = panelZombieNormal.getGraphics();
        g.drawImage(zombie.getImage(), 0, 0, zombie.getIconWidth(), zombie.getIconHeight(), this);
        g = panelZombieCono.getGraphics();
        g.drawImage(zombieCono.getImage(), 0, 0, zombieCono.getIconWidth(), zombieCono.getIconHeight(), this);
        g = panelZombieCubo.getGraphics();
        g.drawImage(zombieCubo.getImage(), 0, 0, zombieCubo.getIconWidth(), zombieCubo.getIconHeight(), this);
        g = panelZombiePuerta.getGraphics();
        g.drawImage(zombiePuerta.getImage(), 0, 0, zombiePuerta.getIconWidth(), zombiePuerta.getIconHeight(), this);
        g = panelZombieLanza.getGraphics();
        g.drawImage(zombieLanza.getImage(), 0, 0, zombieLanza.getIconWidth(), zombieLanza.getIconHeight(), this);
        g = panelZombieLoco.getGraphics();
        g.drawImage(zombieLoco.getImage(), 0, 0, zombieLoco.getIconWidth(), zombieLoco.getIconHeight(), this);
        g = panelZombieGlobo.getGraphics();
        g.drawImage(zombieGlobo.getImage(), 0, 0, zombieGlobo.getIconWidth(), zombieGlobo.getIconHeight(), this);
        g = panelZombieMinero.getGraphics();
        g.drawImage(zombieMinero.getImage(), 0, 0, zombieMinero.getIconWidth(), zombieMinero.getIconHeight(), this);
        g = panelZombieYeti.getGraphics();
        g.drawImage(zombieYeti.getImage(), 0, 0, zombieYeti.getIconWidth(), zombieYeti.getIconHeight(), this);
        g = panelZombieGigante.getGraphics();
        g.drawImage(zombieGigante.getImage(), 0, 0, zombieGigante.getIconWidth(), zombieGigante.getIconHeight(), this);
        g = panelZombieCatapulta.getGraphics();
        g.drawImage(zombieCatapulta.getImage(), 0, 0, zombieCatapulta.getIconWidth(), zombieCatapulta.getIconHeight(), this);
        g = panelZombiePeriodico.getGraphics();
        g.drawImage(zombiePeriodico.getImage(), 0, 0, zombiePeriodico.getIconWidth(), zombiePeriodico.getIconHeight(), this);
        g = panelZombieRugby.getGraphics();
        g.drawImage(zombieRugby.getImage(), 0, 0, zombieRugby.getIconWidth(), zombieRugby.getIconHeight(), this);
    }

    private void panelZombieNormalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelZombieNormalMouseClicked
        if( empezarAElegir )
        {
            boolean encontrado = false;
            ListIterator i = zombs.listIterator();
            while (!encontrado && i.hasNext())
            {
                zombie aux = ((zombie)i.next());
                encontrado = aux.getNombre().equals("Zombie");
            }
            if( encontrado )
            {
                zombi = new zombie("Zombie", 20, 30);
                fil = Integer.parseInt(textoFilaZombie.getText());
                JOptionPane.showMessageDialog(this, "¡Elegido el zombie normal!");
            }
            else
                JOptionPane.showMessageDialog(this, "¡No has elegido antes al zombie normal!");
        }
}//GEN-LAST:event_panelZombieNormalMouseClicked

    private void panelZombieConoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelZombieConoMouseClicked
        if( empezarAElegir )
        {
            boolean encontrado = false;
            ListIterator i = zombs.listIterator();
            while (!encontrado && i.hasNext())
            {
                zombie aux = ((zombie)i.next());
                encontrado = aux.getNombre().equals("ZombieCaracono");
            }
            if( encontrado )
            {
                zombi = new zombie("ZombieCaracono", 20, 40);
                fil = Integer.parseInt(textoFilaZombie.getText());
                JOptionPane.showMessageDialog(this, "¡Elegido el zombie caracono!");
            }
            else
                JOptionPane.showMessageDialog(this, "¡No has elegido antes al zombie caracono!");
        }
}//GEN-LAST:event_panelZombieConoMouseClicked

    private void panelZombieCuboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelZombieCuboMouseClicked
        if( empezarAElegir )
        {
            boolean encontrado = false;
            ListIterator i = zombs.listIterator();
            while (!encontrado && i.hasNext())
            {
                zombie aux = ((zombie)i.next());
                encontrado = aux.getNombre().equals("ZombieCubililetero");
            }
            if( encontrado )
            {
                zombi = new zombie("ZombieCubililetero", 20, 50);
                fil = Integer.parseInt(textoFilaZombie.getText());
                JOptionPane.showMessageDialog(this, "¡Elegido el zombie cubililetero!");
            }
            else
                JOptionPane.showMessageDialog(this, "¡No has elegido antes al zombie cubililetero!");
        }
}//GEN-LAST:event_panelZombieCuboMouseClicked

    private void panelZombiePeriodicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelZombiePeriodicoMouseClicked
        if( empezarAElegir )
        {
            boolean encontrado = false;
            ListIterator i = zombs.listIterator();
            while (!encontrado && i.hasNext())
            {
                zombie aux = ((zombie)i.next());
                encontrado = aux.getNombre().equals("ZombieLector");
            }
            if( encontrado )
            {
                zombi = new zombie("ZombieLector", 20, 35);
                fil = Integer.parseInt(textoFilaZombie.getText());
                JOptionPane.showMessageDialog(this, "¡Elegido el zombie lector!");
            }
            else
                JOptionPane.showMessageDialog(this, "¡No has elegido antes al zombie lector!");
        }
}//GEN-LAST:event_panelZombiePeriodicoMouseClicked

    private void panelZombiePuertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelZombiePuertaMouseClicked
        if( empezarAElegir )
        {
            boolean encontrado = false;
            ListIterator i = zombs.listIterator();
            while (!encontrado && i.hasNext())
            {
                zombie aux = ((zombie)i.next());
                encontrado = aux.getNombre().equals("ZombiePortero");
            }
            if( encontrado )
            {
                zombi = new zombie("ZombiePortero", 20, 45);
                fil = Integer.parseInt(textoFilaZombie.getText());
                JOptionPane.showMessageDialog(this, "¡Elegido el zombie portero!");
            }
            else
                JOptionPane.showMessageDialog(this, "¡No has elegido antes al zombie portero!");
        }
}//GEN-LAST:event_panelZombiePuertaMouseClicked

    private void panelZombieLanzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelZombieLanzaMouseClicked
        if( empezarAElegir )
        {
            boolean encontrado = false;
            ListIterator i = zombs.listIterator();
            while (!encontrado && i.hasNext())
            {
                zombie aux = ((zombie)i.next());
                encontrado = aux.getNombre().equals("ZombieSaltador");
            }
            if( encontrado )
            {
                zombi = new zombie("ZombieSaltador", 20, 30);
                fil = Integer.parseInt(textoFilaZombie.getText());
                JOptionPane.showMessageDialog(this, "¡Elegido el zombie saltador!");
            }
            else
                JOptionPane.showMessageDialog(this, "¡No has elegido antes al zombie saltador!");
        }
}//GEN-LAST:event_panelZombieLanzaMouseClicked

    private void panelZombieCatapultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelZombieCatapultaMouseClicked
        if( empezarAElegir )
        {
            boolean encontrado = false;
            ListIterator i = zombs.listIterator();
            while (!encontrado && i.hasNext())
            {
                zombie aux = ((zombie)i.next());
                encontrado = aux.getNombre().equals("Zombipulta");
            }
            if( encontrado )
            {
                zombi = new zombie("Zombipulta", 25, 40);
                fil = Integer.parseInt(textoFilaZombie.getText());
                JOptionPane.showMessageDialog(this, "¡Elegido el zombipulta!");
            }
            else
                JOptionPane.showMessageDialog(this, "¡No has elegido antes al zombipulta!");
        }
}//GEN-LAST:event_panelZombieCatapultaMouseClicked

    private void panelZombieGiganteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelZombieGiganteMouseClicked
        if( empezarAElegir )
        {
            boolean encontrado = false;
            ListIterator i = zombs.listIterator();
            while (!encontrado && i.hasNext())
            {
                zombie aux = ((zombie)i.next());
                encontrado = aux.getNombre().equals("Zombistein");
            }
            if( encontrado )
            {
                zombi = new zombie("Zombistein", 100, 100);
                fil = Integer.parseInt(textoFilaZombie.getText());
                JOptionPane.showMessageDialog(this, "¡Elegido el zombistein!");
            }
            else
                JOptionPane.showMessageDialog(this, "¡No has elegido antes al zombistein!");
        }
}//GEN-LAST:event_panelZombieGiganteMouseClicked

    private void panelZombieMineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelZombieMineroMouseClicked
        if( empezarAElegir )
        {
            boolean encontrado = false;
            ListIterator i = zombs.listIterator();
            while (!encontrado && i.hasNext())
            {
                zombie aux = ((zombie)i.next());
                encontrado = aux.getNombre().equals("ZombieMinero");
            }
            if( encontrado )
            {
                zombi = new zombie("ZombieMinero", 20, 30);
                fil = Integer.parseInt(textoFilaZombie.getText());
                JOptionPane.showMessageDialog(this, "¡Elegido el zombie minero!");
            }
            else
                JOptionPane.showMessageDialog(this, "¡No has elegido antes al zombie minero!");
        }
}//GEN-LAST:event_panelZombieMineroMouseClicked

    private void panelZombieGloboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelZombieGloboMouseClicked
        if( empezarAElegir )
        {
            boolean encontrado = false;
            ListIterator i = zombs.listIterator();
            while (!encontrado && i.hasNext())
            {
                zombie aux = ((zombie)i.next());
                encontrado = aux.getNombre().equals("ZombieGlobo");
            }
            if( encontrado )
            {
                zombi = new zombie("ZombieGlobo", 20, 30);
                fil = Integer.parseInt(textoFilaZombie.getText());
                JOptionPane.showMessageDialog(this, "¡Elegido el zombie con globo!");
            }
            else
                JOptionPane.showMessageDialog(this, "¡No has elegido antes al zombie con globo!");
        }
}//GEN-LAST:event_panelZombieGloboMouseClicked

    private void panelZombieLocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelZombieLocoMouseClicked
        if( empezarAElegir )
        {
            boolean encontrado = false;
            ListIterator i = zombs.listIterator();
            while (!encontrado && i.hasNext())
            {
                zombie aux = ((zombie)i.next());
                encontrado = aux.getNombre().equals("ZombieLoco");
            }
            if( encontrado )
            {
                zombi = new zombie("ZombieLoco", 40, 30);
                fil = Integer.parseInt(textoFilaZombie.getText());
                JOptionPane.showMessageDialog(this, "¡Elegido el zombie con cajita!");
            }
            else
                JOptionPane.showMessageDialog(this, "¡No has elegido antes al zombie con cajita!");
        }
}//GEN-LAST:event_panelZombieLocoMouseClicked

    private void panelZombieYetiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelZombieYetiMouseClicked
        if( empezarAElegir )
        {
            boolean encontrado = false;
            ListIterator i = zombs.listIterator();
            while (!encontrado && i.hasNext())
            {
                zombie aux = ((zombie)i.next());
                encontrado = aux.getNombre().equals("ZombieYeti");
            }
            if( encontrado )
            {
                zombi = new zombie("ZombieYeti", 80, 60);
                fil = Integer.parseInt(textoFilaZombie.getText());
                JOptionPane.showMessageDialog(this, "¡Elegido el zombie yeti!");
            }
            else
                JOptionPane.showMessageDialog(this, "¡No has elegido antes al zombie yeti!");
        }
}//GEN-LAST:event_panelZombieYetiMouseClicked

    private void panelZombieRugbyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelZombieRugbyMouseClicked
        if( empezarAElegir )
        {
            boolean encontrado = false;
            ListIterator i = zombs.listIterator();
            while (!encontrado && i.hasNext())
            {
                zombie aux = ((zombie)i.next());
                encontrado = aux.getNombre().equals("ZombieDeportista");
            }
            if( encontrado )
            {
                zombi = new zombie("ZombieDeportista", 20, 60);
                fil = Integer.parseInt(textoFilaZombie.getText());
                JOptionPane.showMessageDialog(this, "¡Elegido el zombie deportista!");
            }
            else
                JOptionPane.showMessageDialog(this, "¡No has elegido antes al zombie deportista!");
        }
}//GEN-LAST:event_panelZombieRugbyMouseClicked

    private void botonElegirZombieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonElegirZombieMouseClicked
        
}//GEN-LAST:event_botonElegirZombieMouseClicked

    private void botonElegirZombieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElegirZombieActionPerformed
        if( Integer.parseInt(textoFilaZombie.getText()) < 0 || Integer.parseInt(textoFilaZombie.getText()) >= 5 )
               JOptionPane.showMessageDialog(this, "¡La fila ha de estar entre 0 y 4!");
        else
        {
            empezarAElegir = true;
            fil = Integer.parseInt(textoFilaZombie.getText());
            botonElegirZombie.setEnabled(false);
            textoFilaZombie.setEnabled(false);
        }
    }//GEN-LAST:event_botonElegirZombieActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new elegirZombieQueViene().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonElegirZombie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelZombieCatapulta;
    private javax.swing.JPanel panelZombieCono;
    private javax.swing.JPanel panelZombieCubo;
    private javax.swing.JPanel panelZombieGigante;
    private javax.swing.JPanel panelZombieGlobo;
    private javax.swing.JPanel panelZombieLanza;
    private javax.swing.JPanel panelZombieLoco;
    private javax.swing.JPanel panelZombieMinero;
    private javax.swing.JPanel panelZombieNormal;
    private javax.swing.JPanel panelZombiePeriodico;
    private javax.swing.JPanel panelZombiePuerta;
    private javax.swing.JPanel panelZombieRugby;
    private javax.swing.JPanel panelZombieYeti;
    private javax.swing.JTextField textoFilaZombie;
    // End of variables declaration//GEN-END:variables

}
