/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * principal.java
 *
 * Created on 18-may-2011, 16:27:56
 */

package plantasvszombies;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author francis
 */
public class principal extends javax.swing.JFrame {

    private ImageIcon icono = new ImageIcon("imagenes/fondo.png");
    private ArrayList arrayPlantas = new ArrayList();
    private ArrayList arrayZombies = new ArrayList();

    @Override
    public void paint(Graphics g)
    {
        super.paintComponents(g);
        g = jPanel1.getGraphics();
        int width_inicial = (jPanel1.getWidth()/2) - (icono.getIconWidth()/2);
        int height_inicial = (jPanel1.getHeight()/2) - (icono.getIconHeight()/2);
        g.drawImage(icono.getImage(), width_inicial, height_inicial, icono.getIconWidth(), icono.getIconHeight(), this);
    }

    /** Creates new form principal */
    public principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonSimularPartida = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuElegir = new javax.swing.JMenu();
        elegirPlantas = new javax.swing.JMenuItem();
        elegirZombies = new javax.swing.JMenuItem();
        menuAcercaDe = new javax.swing.JMenu();
        acercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plantas VS Zombies Strategist");

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 279));

        botonSimularPartida.setText("Simular partida");
        botonSimularPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSimularPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(botonSimularPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonSimularPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        menuElegir.setText("Elegir");
        menuElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuElegirActionPerformed(evt);
            }
        });

        elegirPlantas.setText("Plantas");
        elegirPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirPlantasActionPerformed(evt);
            }
        });
        menuElegir.add(elegirPlantas);

        elegirZombies.setText("Zombies");
        elegirZombies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirZombiesActionPerformed(evt);
            }
        });
        menuElegir.add(elegirZombies);

        jMenuBar1.add(menuElegir);

        menuAcercaDe.setText("Acerca de");

        acercaDe.setText("Acerca de Plantas VS Zombies Strategist");
        acercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDeActionPerformed(evt);
            }
        });
        menuAcercaDe.add(acercaDe);

        jMenuBar1.add(menuAcercaDe);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSimularPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSimularPartidaActionPerformed
        if( arrayPlantas.size() > 0 && arrayZombies.size() > 0 )
        {
            Tablero miJardin = new Tablero (arrayPlantas, arrayZombies);
            miJardin.setTitle("Simulación de juego");
            miJardin.setSize(1220, 700);
            miJardin.setVisible(true);
        }
        else
            if(arrayPlantas.size() == 0 && arrayZombies.size() == 0)
                JOptionPane.showMessageDialog(this, "Elige las plantas y los zombies");
            else
                if( arrayPlantas.size() == 0 )
                    JOptionPane.showMessageDialog(this, "Elige las plantas");
                else
                    JOptionPane.showMessageDialog(this, "Elige los zombies");
    }//GEN-LAST:event_botonSimularPartidaActionPerformed

    private void menuElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuElegirActionPerformed

    }//GEN-LAST:event_menuElegirActionPerformed

    private void elegirPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirPlantasActionPerformed
        elegirPlantitas ventanaElegirPlantas = null;
        try {
            ventanaElegirPlantas = new elegirPlantitas(arrayPlantas);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventanaElegirPlantas.setTitle("Elige las plantas! que vienen los zombies!");
        ventanaElegirPlantas.setSize(700,500);
        // ***** Centro la ventana *****
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = ventanaElegirPlantas.getSize();
        if (frameSize.height > screenSize.height)
            frameSize.height = screenSize.height;
        if (frameSize.width > screenSize.width)
            frameSize.width = screenSize.width;
        ventanaElegirPlantas.setLocation( (screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        // *****************************
        ventanaElegirPlantas.setVisible(true);
    }//GEN-LAST:event_elegirPlantasActionPerformed

    private void elegirZombiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirZombiesActionPerformed
        elegirZombies ventanaElegirZombies = null;
        try {
            ventanaElegirZombies = new elegirZombies(arrayZombies);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventanaElegirZombies.setTitle("Elige los zombies que te van a atacar");
        ventanaElegirZombies.setSize(750,430);
        // ***** Centro la ventana *****
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = ventanaElegirZombies.getSize();
        if (frameSize.height > screenSize.height)
            frameSize.height = screenSize.height;
        if (frameSize.width > screenSize.width)
            frameSize.width = screenSize.width;
        ventanaElegirZombies.setLocation( (screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        // *****************************
        ventanaElegirZombies.setVisible(true);
    }//GEN-LAST:event_elegirZombiesActionPerformed

    private void acercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeActionPerformed
        String texto = "Plantas VS Zombies Strategist";
        texto += "\nPráctica SAD 2.010 - 2.011";
        texto += "\nAutores:";
        texto += "\nFrancisco Jesús Delgado Almirón";
        texto += "\nJavier de Castro Blasco";
        JOptionPane.showMessageDialog(this, texto);
    }//GEN-LAST:event_acercaDeActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acercaDe;
    private javax.swing.JButton botonSimularPartida;
    private javax.swing.JMenuItem elegirPlantas;
    private javax.swing.JMenuItem elegirZombies;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenu menuElegir;
    // End of variables declaration//GEN-END:variables

}
